package com.example.drop.wzjtestapp.database.greendao;

import com.example.drop.wzjtestapp.database.db.SearchSave;
import com.example.drop.wzjtestapp.database.db.StockProductSave;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchSaveDaoConfig;
    private final DaoConfig stockProductSaveDaoConfig;

    private final SearchSaveDao searchSaveDao;
    private final StockProductSaveDao stockProductSaveDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchSaveDaoConfig = daoConfigMap.get(SearchSaveDao.class).clone();
        searchSaveDaoConfig.initIdentityScope(type);

        stockProductSaveDaoConfig = daoConfigMap.get(StockProductSaveDao.class).clone();
        stockProductSaveDaoConfig.initIdentityScope(type);

        searchSaveDao = new SearchSaveDao(searchSaveDaoConfig, this);
        stockProductSaveDao = new StockProductSaveDao(stockProductSaveDaoConfig, this);

        registerDao(SearchSave.class, searchSaveDao);
        registerDao(StockProductSave.class, stockProductSaveDao);
    }
    
    public void clear() {
        searchSaveDaoConfig.clearIdentityScope();
        stockProductSaveDaoConfig.clearIdentityScope();
    }

    public SearchSaveDao getSearchSaveDao() {
        return searchSaveDao;
    }

    public StockProductSaveDao getStockProductSaveDao() {
        return stockProductSaveDao;
    }

}
